version: 2
updates:

  # Config for backend-dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      backend-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"

  # Config for Docker Compose dependencies
  - package-ecosystem: "docker-compose"
    directories:
      - "/stack"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    assignees:
      - "emaarco"
    groups:
      docker-compose:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"